version: "3.8"

services:

  service_a:
    build: ./Service_a
    container_name: Service_a
    volumes:
      - "C:/Users/user/Downloads/podcasts/podcasts:/podcasts"
    environment:
      PYTHONUNBUFFERED: 1
      PROJECT_DIR: ../tweet_podcasts
      SRC_PATH: /podcasts
      TOPIC_METADATA: metadata
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      HOST_ELASTICSEARCH: http://elasticsearch:9200

    depends_on:
      kafka:
        condition: service_healthy


  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
      container_name: elasticsearch
      environment:
        - node.name=elasticsearch
        - discovery.type=single-node
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      healthcheck:
        test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9200 && echo -e 'GET /_cluster/health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -vq '\"status\":\"red\"'"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 20s


  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_kraft:/var/lib/kafka/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

volumes:
  kafka_kraft:
  esdata:
    driver: local